export interface PeriodicElement {
  email: string;
  id: number;
  identification: number;
  first_name: string;
  last_name: string;
  role: string;
  state: string;
  phone: string;
}

export const ELEMENT_DATA: PeriodicElement[] = [
  {
    id: 1,
    first_name: 'Andrés Felipe',
    last_name: 'Garcia Castro',
    identification: 114485404,
    email: 'afgarcia@refinal.com',
    state: 'Activo',
    role: 'Administrador',
    phone: '3212452342',
  },
  {
    id: 2,
    first_name: 'Andrés Felipe',
    last_name: 'Garcia Castro',
    identification: 114485404,
    email: 'afgarcia@refinal.com',
    state: 'Activo',
    role: 'Administrador',
    phone: '3212452342',
  },
  {
    id: 3,
    first_name: 'Andrés Felipe',
    last_name: 'Garcia Castro',
    identification: 114485404,
    email: 'afgarcia@refinal.com',
    state: 'Activo',
    role: 'Administrador',
    phone: '3212452342',
  },
  {
    id: 4,
    first_name: 'Andrés Felipe',
    last_name: 'Garcia Castro',
    identification: 114485404,
    email: 'afgarcia@refinal.com',
    state: 'Activo',
    role: 'Administrador',
    phone: '3212452342',
  },
  {
    id: 5,
    first_name: 'Andrés Felipe',
    last_name: 'Garcia Castro',
    identification: 114485404,
    email: 'afgarcia@refinal.com',
    state: 'Activo',
    role: 'Administrador',
    phone: '3212452342',
  },
  {
    id: 6,
    first_name: 'Andrés Felipe',
    last_name: 'Garcia Castro',
    identification: 114485404,
    email: 'afgarcia@refinal.com',
    state: 'Activo',
    role: 'Administrador',
    phone: '3212452342',
  },
  {
    id: 7,
    first_name: 'Andrés Felipe',
    last_name: 'Garcia Castro',
    identification: 114485404,
    email: 'afgarcia@refinal.com',
    state: 'Activo',
    role: 'Administrador',
    phone: '3212452342',
  },
  {
    id: 8,
    first_name: 'Andrés Felipe',
    last_name: 'Garcia Castro',
    identification: 114485404,
    email: 'afgarcia@refinal.com',
    state: 'Activo',
    role: 'Administrador',
    phone: '3212452342',
  },
  {
    id: 9,
    first_name: 'Andrés Felipe',
    last_name: 'Garcia Castro',
    identification: 114485404,
    email: 'afgarcia@refinal.com',
    state: 'Activo',
    role: 'Administrador',
    phone: '3212452342',
  },
  {
    id: 10,
    first_name: 'Andrés Felipe',
    last_name: 'Garcia Castro',
    identification: 114485404,
    email: 'afgarcia@refinal.com',
    state: 'Activo',
    role: 'Administrador',
    phone: '3212452342',
  },
  {
    id: 11,
    first_name: 'Andrés Felipe',
    last_name: 'Garcia Castro',
    identification: 114485404,
    email: 'afgarcia@refinal.com',
    state: 'Activo',
    role: 'Administrador',
    phone: '3212452342',
  },
  {
    id: 12,
    first_name: 'Andrés Felipe',
    last_name: 'Garcia Castro',
    identification: 114485404,
    email: 'afgarcia@refinal.com',
    state: 'Activo',
    role: 'Administrador',
    phone: '3212452342',
  },
  {
    id: 13,
    first_name: 'Andrés Felipe',
    last_name: 'Garcia Castro',
    identification: 114485404,
    email: 'afgarcia@refinal.com',
    state: 'Activo',
    role: 'Administrador',
    phone: '3212452342',
  },
  {
    id: 14,
    first_name: 'Andrés Felipe',
    last_name: 'Garcia Castro',
    identification: 114485404,
    email: 'afgarcia@refinal.com',
    state: 'Activo',
    role: 'Administrador',
    phone: '3212452342',
  },
  {
    id: 15,
    first_name: 'Andrés Felipe',
    last_name: 'Garcia Castro',
    identification: 114485404,
    email: 'afgarcia@refinal.com',
    state: 'Activo',
    role: 'Administrador',
    phone: '3212452342',
  },
  {
    id: 16,
    first_name: 'Andrés Felipe',
    last_name: 'Garcia Castro',
    identification: 114485404,
    email: 'afgarcia@refinal.com',
    state: 'Activo',
    role: 'Administrador',
    phone: '3212452342',
  },
  {
    id: 17,
    first_name: 'Andrés Felipe',
    last_name: 'Garcia Castro',
    identification: 114485404,
    email: 'afgarcia@refinal.com',
    state: 'Activo',
    role: 'Administrador',
    phone: '3212452342',
  },
  {
    id: 18,
    first_name: 'Andrés Felipe',
    last_name: 'Garcia Castro',
    identification: 114485404,
    email: 'afgarcia@refinal.com',
    state: 'Activo',
    role: 'Administrador',
    phone: '3212452342',
  },
  {
    id: 19,
    first_name: 'Andrés Felipe',
    last_name: 'Garcia Castro',
    identification: 114485404,
    email: 'afgarcia@refinal.com',
    state: 'Activo',
    role: 'Administrador',
    phone: '3212452342',
  },
  {
    id: 20,
    first_name: 'Andrés Felipe',
    last_name: 'Garcia Castro',
    identification: 114485404,
    email: 'afgarcia@refinal.com',
    state: 'Activo',
    role: 'Administrador',
    phone: '3212452342',
  },
  {
    id: 21,
    first_name: 'Andrés Felipe',
    last_name: 'Garcia Castro',
    identification: 114485404,
    email: 'afgarcia@refinal.com',
    state: 'Activo',
    role: 'Administrador',
    phone: '3212452342',
  },
];
